### ISSUE TITLE
Repo for proceeding submission

### ISSUE THREAD

**Issue by htwangtw** [ohbm/hackathon2022proceedings#1]
I realised people are submitting their PRs to [the template repo](https://github.com/ohbm/hackathon_proceedings_templates) instead of this one. Shall we redirect people to here?

**Comment by smoia** [comment]
Might be my fault - I might have sent the wrong link in the email. Let's use that one and I'll wipe it clean once done.

**Comment by smoia** [comment]
Nope, email and README have the right link. I'll pull-and-push things around to get things here.

**Comment by htwangtw** [comment]
Let's close this issue since we have that PR migrating things now
